# Generated by Django 5.1.7 on 2025-10-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(db_index=True, max_length=128)),
                ('device_submitted_at', models.DateTimeField()),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('level_after', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teams.team')),
            ],
            options={
                'ordering': ['-server_received_at'],
                'indexes': [models.Index(fields=['team_code', 'server_received_at'], name='teams_submi_team_co_8e9137_idx')],
            },
        ),
    ]
