# Generated by Django 5.1.7 on 2025-10-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-level_after', 'last_submitted_at']},
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='teams_submi_team_co_8e9137_idx',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='server_received_at',
        ),
        migrations.AddField(
            model_name='submission',
            name='last_submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='device_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='level_after',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='team_code',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
